name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:

  test:
    name: CI

    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    
    - name: Check out repo
      if: always()
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      if: always()

    - name: Install
      if: always()
      run: |
        python3 -m venv venv 
        source venv/bin/activate
        python3 -m pip install .

    - name: Run tests
      if: always()
      run: |
        source venv/bin/activate
        python3 tests/warden_tests.py
